/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.utptest;

public class myutp {
  public static int send() {
    return myutpJNI.send();
  }

  public static int listen() {
    return myutpJNI.listen();
  }

}
